<template>
  <div class="blog1">
    <h5 class="back">
      <router-link to="/blog">Back</router-link>
    </h5>
    <h1>Money and Bitcoin, Keys and Coins</h1>
    <h3>by Jeremy Garcia - May 11, 2022</h3>
    <h5>
      <a href="https://satoshisjournal.com/money-and-bitcoin-keys-and-coins/">
        Original Article host on Satoshi's Journal and shared with
        permission.</a
      >
    </h5>
    <h2>What is Money?</h2>
    <p>
      We work our entire life to earn money to provide for our families,
      therefore, the money you work for needs to be a good store of value,
      right? What makes money a good store of value? The perfect money should
      be:
    </p>
    <ul>
      <li>Durable</li>
      <li>Portable</li>
      <li>Scalable</li>
      <li>Saleable</li>
      <li>Limited Supply</li>
      <li>Scarce</li>
      <li>Fungible</li>
      <li>Trusted</li>
      <li>Divisible</li>
      <li>Un-confiscatable</li>
    </ul>
    <p>
      For thousands of years, Gold was considered to be the best store of value.
      Bitcoin has taken this status away from Gold because Bitcoin meets all of
      the requirements of a good store of value and more.
    </p>
    <h2>What is Bitcoin?</h2>
    <p>
      Bitcoin is money on a ledger. Bitcoin, spelled with a “Big B” is the
      ledger and bitcoin, spelled with a “little b” is the money. What is a
      ledger? A ledger is a list of transactions that have been made between
      people that are buying and selling goods from each other. Traditionally,
      ledgers have always needed a central authority that was responsible for
      verifying transactions between two people. This system required that
      people trust the central authority to correctly write down the amounts
      owed or collected and to not change the ledger for his/her gain. Bitcoin
      is a ledger that anyone in the world can see. All transactions are not
      verified by a central authority. Instead, the transactions on the Bitcoin
      ledger are verified by 1000’s of “nodes” that have individual copies of
      the entire ledger. If any of the 1000’s of nodes see two parties that are
      trying to spend bitcoin they don’t have, the nodes will reject that
      transaction. This is why Bitcoin is a trustless system and why it makes
      the Bitcoin ledger the most powerful invention ever known to mankind.
      Bitcoin is a once in a species discovery!
    </p>
    <h2>Why Do We Need Bitcoin?</h2>
    <p>
      We need Bitcoin because for 1000’s of years central authorities have
      always controlled and corrupted money. They have done this by stealing
      people’s hard work through debasement, known as inflation. Inflation is
      simply the ability for central authorities to be able to create more
      money, which dilutes the value of your hard work. Bitcoin cannot be
      controlled by anyone and is limited to a supply of 21 million bitcoin.
      This limited supply eliminates the ability for inflation to occur.
      Inflation is an insidious tax that slowly steals the value of the money
      you earn from your governments.
    </p>
    <h2>How Do You Buy Bitcoin?</h2>
    <p>
      You can simply buy bitcoin on an exchange like Swan Bitcoin or Botmecash
      which are Bitcoin-only exchanges. Once you buy your bitcoin, it is
      important that you learn how to self custody it. When you buy bitcoin on
      an exchange, the bitcoin is not yours because it is held on the exchange.
      If something bad were to happen to the exchange you are using, you might
      not have access to your bitcoin forever!
    </p>
    <h2>How Do You Store you bitcoin?</h2>
    <p>
      When you are ready to take your bitcoin off an exchange so that you can
      self-custody, you will have to buy a cold wallet. There are two types of
      wallets, hot wallets and cold wallets. A hot wallet is connected to the
      internet and and cold wallet is not connected to the internet. One very
      important note is that bitcoin IS NOT stored on your cold wallet. Instead,
      your cold wallet generates and stores your public and private keys. A
      public key is like an email address that allows anyone to send you
      bitcoin. The private keys are a series of 12-24 words generated by your
      cold wallet that give you exclusive rights to your bitcoin. The reason why
      you want to self custody your bitcoin in a cold wallet is because it is
      protected from any person on the internet gaining access to your private
      keys. This is no different than a person storing their gold in a secret
      chest (cold wallet) that they only know about, versus holding their gold
      in the bank (exchange), where the bankers can confiscate it.
    </p>
    <h2>Not You Keys, Not your Coin</h2>
    <p>
      The common phrase among Bitcoiners, “Not your Keys, Not your Coins,” means
      that if you don’t have the 12-24 keywords that your cold wallet generates
      for you, you don’t own your bitcoin. These 12-24 key words are the only
      way for you to be able to prove ownership of your bitcoin. Store them in a
      safe place, never share them with anyone, don’t store them on a computer,
      don’t take pictures of them and never lose them, because if you do, you
      will forever lose your bitcoin.
    </p>
  </div>
</template>
<script lang="ts">
import { defineComponent } from "vue";

export default defineComponent({
  name: "Blog1",
});
</script>
<style scoped>
.blog1 {
  padding: 20px;
  align-self: center;
  align-content: center;
  max-width: 680px;
  margin: auto;
  background-color: #fafafa;
}

.back {
  text-align: left;
  position: fixed;
  top: 0;
  width: fit-content;
  z-index: 100;
  background-color: #fafafa;
}

h3 {
  margin: 40px 0 0;
}

ul {
  list-style-type: disc;
  padding: 0;
  margin: auto;
  max-width: fit-content;
}

li {
  margin: 10px 10px;
  text-align: left;
}

a {
  color: #42b983;
}

p {
  word-break: break-word;
  overflow-wrap: break-word;
}
</style>
